### PR TITLE
TH-1003 | Remove blue color from background color list

### PR DESCRIPTION
**Pull request by quyenlq**
### Closes :no_good_woman:
**[TH-XXX](https://helsinkisolutionoffice.atlassian.net/browse/TH-XXX):**

### CODE REVIEW

**Review by nikomakela — CHANGES_REQUESTED** [review]
Should there be a data migration for a removed value? Wouldn't it lead to a key constraint error if the removed value is stored for some instances?

Done changes looks good.

**Comment by quyenlq** [comment]
Good point @nikomakela. This field doesn't have any constraint in the DB, remove the Blue color choice will make the old data become blank. I thought this was enough but no 😅, the background color is required so yes we indeed need to migrate the old color to another available one. Update this PR soon...

**Comment by nikomakela** [comment]
> Good point @nikomakela. This field doesn't have any constraint in the DB, remove the Blue color choice will make the old data become blank. I thought this was enough but no 😅, the background color is required so yes we indeed need to migrate the old color to another available one. Update this PR soon...

I didn't even know that Django would blank the fields... Good that it does. But yeah, this wasn't a false call after all if the color is mandatory.

**Comment by quyenlq** [comment]
I asked Mari and Tomi Alto what would be the fallback color for this, but they said there isn't any banner/collection using that blue color at the moment so just leave it empty for now.  The content provider can always manually update it in the Wagtail admin later so this doesn't break anything

**Review by nikomakela — APPROVED** [review]

**Comment by nikomakela** [comment]
> I asked Mari and Tomi Alto what would be the fallback color for this, but they said there isn't any banner/collection using that blue color at the moment so just leave it empty for now. The content provider can always manually update it in the Wagtail admin later so this doesn't break anything

I have used the colour in my local machine, so in that sense it might have been good to migrate it away, but I can manage without. :)

**Pull request merged**
